name: Live Streams M3U

on:
  schedule:
    - cron: "*/20 * * * *"  # every 20 minutes
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: live-m3u
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SCRIPT_PATH: streamed_ultra.py  # change if your script has a different name or path
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install system deps
        run: |
          
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends
          xvfb
          libgbm1
          libgtk-3-0
          libnss3
          libxss1
          libasound2t64
          fonts-liberation
          xdg-utils
          libu2f-udev

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper under Xvfb (non-headless Chrome)
        run: |
          xvfb-run -a python "$SCRIPT_PATH"

      - name: Commit and push changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Update playlists: $(date -u +"%Y-%m-%d %H:%M:%S") UTC"
            git push
          else
            echo "No changes to commit"
          fi
